import type { ComponentMeta } from "../../registry.types";

export const navigationPanelMeta = {
  category: "navigation",
  description: "A scrollable application navigation panel with independent header, grouped content, selected items, and footer slots.",
  maturity: "stable",
  name: "NavigationPanel",
  props: [
    { name: "children", type: "ReactNode" },
    { name: "header", type: "ReactNode" },
    { name: "footer", type: "ReactNode" },
    { name: "bodyRef", type: "Ref<HTMLDivElement>" },
    { name: "bodyClassName", type: "string" },
    { name: "contentClassName", type: "string" },
    { defaultValue: "auto", name: "scrollbarVisibility", type: "auto | always | hidden" },
  ],
  states: ["default", "selected-item", "disabled-item", "scrolling"],
  tokens: [
    "color.surface.subtle",
    "color.border.subtle",
    "color.content.muted",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfacePressed",
    "color.focus.ring",
    "font.family.control",
    "font.weight.medium",
    "font.weight.semibold",
    "layout.navigationPanel.inlineSize",
    "layout.navigationPanel.surfacePadding",
    "layout.navigationPanel.contentGap",
    "layout.navigationPanel.sectionGap",
    "layout.navigationPanel.headingHeight",
    "layout.navigationPanel.headingPaddingInline",
    "layout.navigationPanel.headingGap",
    "layout.navigationPanel.headingFontSize",
    "layout.navigationPanel.headingActionSize",
    "layout.navigationPanel.itemHeight",
    "layout.navigationPanel.itemPaddingInline",
    "layout.navigationPanel.itemGap",
    "layout.navigationPanel.itemRadius",
    "layout.navigationPanel.itemIconSize",
    "layout.navigationPanel.scrollbarGap",
    "layout.navigationPanel.footerHeight",
    "layout.navigationPanel.footerPadding",
    "scrollbar.width",
    "scrollbar.radius",
  ],
} as const satisfies ComponentMeta;
