export type WidgetThemePayload = {
  id: string;
  type: string;
  vars: Record<string, string>;
};

const THEME_VAR_NAMES = [
  '--color-bg-primary',
  '--color-static-white',
  '--color-static-black',
  '--color-overlay-white-02',
  '--color-overlay-white-03',
  '--color-overlay-white-04',
  '--color-overlay-white-05',
  '--color-overlay-white-06',
  '--color-overlay-white-08',
  '--color-overlay-white-10',
  '--color-overlay-white-12',
  '--color-overlay-white-15',
  '--color-overlay-white-20',
  '--color-overlay-white-60',
  '--color-overlay-black-06',
  '--color-overlay-black-08',
  '--color-overlay-black-10',
  '--color-overlay-black-12',
  '--color-overlay-black-15',
  '--color-overlay-black-20',
  '--color-overlay-black-25',
  '--color-overlay-black-30',
  '--color-overlay-black-40',
  '--color-overlay-black-50',
  '--color-overlay-black-80',
  '--color-bg-secondary',
  '--color-bg-tertiary',
  '--color-bg-quaternary',
  '--color-bg-elevated',
  '--color-bg-workbench',
  '--color-bg-scene',
  '--color-bg-flowchat',
  '--color-bg-surface',
  '--color-bg-base',
  '--color-bg-subtle',
  '--color-bg-hover',
  '--color-hover',
  '--color-background-secondary',
  '--color-background-tertiary',
  '--background-primary',
  '--background-secondary',
  '--background-tertiary',
  '--bg-primary',
  '--bg-secondary',
  '--bg-tertiary',
  '--bg-elevated',
  '--bg-hover',
  '--color-surface-hover',
  '--color-bg-tooltip',
  '--color-text-primary',
  '--color-text-secondary',
  '--color-text-tertiary',
  '--text-primary',
  '--text-secondary',
  '--text-tertiary',
  '--text-muted',
  '--text-disabled',
  '--color-text-muted',
  '--color-text-disabled',
  '--color-accent-50',
  '--color-accent-100',
  '--color-accent-200',
  '--color-accent-300',
  '--color-accent-400',
  '--color-accent-500',
  '--color-accent-600',
  '--color-accent-700',
  '--color-accent-800',
  '--color-accent',
  '--color-accent-primary',
  '--color-accent-alpha',
  '--color-primary',
  '--color-primary-rgb',
  '--color-primary-400',
  '--color-primary-hover',
  '--color-primary-500',
  '--color-primary-alpha',
  '--accent-primary',
  '--accent-primary-hover',
  '--color-success',
  '--color-success-bg',
  '--color-success-border',
  '--color-success-500',
  '--color-warning',
  '--color-warning-bg',
  '--color-warning-border',
  '--color-warning-500',
  '--color-error',
  '--color-error-bg',
  '--color-error-border',
  '--color-semantic-error',
  '--color-danger',
  '--color-danger-500',
  '--color-danger-text',
  '--color-danger-bg',
  '--color-danger-border',
  '--color-danger-hover',
  '--color-info',
  '--color-info-bg',
  '--color-info-border',
  '--border-subtle',
  '--border-base',
  '--border-medium',
  '--border-strong',
  '--border-prominent',
  '--border-primary',
  '--color-border',
  '--color-border-primary',
  '--color-border-subtle',
  '--element-bg-subtle',
  '--element-bg-soft',
  '--element-bg-base',
  '--element-bg-medium',
  '--element-bg-strong',
  '--element-bg-elevated',
  '--element-bg-hover',
  '--shadow-xs',
  '--shadow-sm',
  '--shadow-base',
  '--shadow-lg',
  '--shadow-xl',
  '--radius-sm',
  '--radius-base',
  '--radius-md',
  '--radius-lg',
  '--radius-xl',
  '--radius-2xl',
  '--radius-full',
  '--size-radius-sm',
  '--size-radius-base',
  '--size-radius-md',
  '--size-radius-lg',
  '--size-radius-xl',
  '--spacing-1',
  '--spacing-2',
  '--spacing-3',
  '--spacing-4',
  '--spacing-5',
  '--spacing-6',
  '--spacing-8',
  '--spacing-10',
  '--spacing-12',
  '--spacing-16',
  '--size-gap-1',
  '--size-gap-2',
  '--size-gap-3',
  '--size-gap-4',
  '--size-gap-5',
  '--size-gap-6',
  '--size-gap-8',
  '--size-gap-10',
  '--size-gap-12',
  '--size-gap-16',
  '--motion-fast',
  '--motion-base',
  '--easing-standard',
  '--font-sans',
  '--font-mono',
] as const;

export function readWidgetThemePayload(): WidgetThemePayload | null {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    return null;
  }

  const root = document.documentElement;
  const styles = window.getComputedStyle(root);
  const vars: Record<string, string> = {};

  for (const name of THEME_VAR_NAMES) {
    const value = styles.getPropertyValue(name).trim();
    if (value) {
      vars[name] = value;
    }
  }

  return {
    id: root.getAttribute('data-theme') || 'unknown',
    type: root.getAttribute('data-theme-type') || 'dark',
    vars,
  };
}
