const WIDGET_THEME_COMPAT_ALIAS_FALLBACKS = {
  '--border-muted': '--border-subtle',
  '--border-primary': '--border-base',
  '--color-background-secondary': '--color-bg-secondary',
  '--color-background-tertiary': '--color-bg-tertiary',
  '--color-bg-base': '--color-bg-primary',
  '--color-bg-elevated-hover': '--element-bg-hover',
  '--color-bg-flowchat': '--color-bg-scene',
  '--color-bg-hover': '--element-bg-hover',
  '--color-bg-subtle': '--element-bg-subtle',
  '--color-bg-surface': '--color-bg-secondary',
  '--color-border': '--border-base',
  '--color-border-primary': '--border-base',
  '--color-border-subtle': '--border-subtle',
  '--color-hover': '--element-bg-hover',
  '--color-semantic-error': '--color-error',
  '--color-success-100': '--color-success-bg',
  '--color-success-500': '--color-success',
  '--color-surface-elevated': '--element-bg-elevated',
  '--color-surface-hover': '--element-bg-hover',
  '--color-text-tertiary': '--color-text-muted',
  '--color-warning-100': '--color-warning-bg',
  '--color-warning-500': '--color-warning',
  '--color-warning-700': '--color-warning',
  '--color-accent': '--color-accent-500',
  '--color-accent-primary': '--color-accent-500',
  '--color-accent-alpha': '--color-accent-100',
  '--color-primary': '--color-accent-500',
  '--color-primary-rgb': '--color-accent-500-rgb',
  '--color-primary-400': '--color-accent-400',
  '--color-primary-hover': '--color-accent-600',
  '--color-primary-500': '--color-accent-500',
  '--color-primary-alpha': '--color-accent-100',
  '--color-primary-bg': '--color-accent-100',
  '--color-primary-bg-subtle': '--color-accent-50',
  '--accent-primary': '--color-accent-500',
  '--accent-primary-hover': '--color-accent-600',
  '--color-danger': '--color-error',
  '--color-danger-500': '--color-error',
  '--color-danger-text': '--color-error',
  '--color-danger-bg': '--color-error-bg',
  '--color-danger-border': '--color-error-border',
  '--color-danger-hover': '--color-error',
  '--element-bg': '--element-bg-base',
  '--font-mono': '--font-family-mono',
  '--font-sans': '--font-family-sans',
  '--markdown-font-mono': '--font-family-mono',
  '--motion-normal': '--motion-base',
  '--secondary-bg': '--color-bg-secondary',
  '--text-tertiary': '--color-text-muted',
  '--tool-compact-summary-font': '--font-family-sans',
} as const;

export function createWidgetThemeCompatibilityAliasCss(): string {
  return Object.entries(WIDGET_THEME_COMPAT_ALIAS_FALLBACKS)
    .map(([name, canonical]) => `      ${name}: var(${canonical});`)
    .join('\n');
}
