import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance/types';

export const toolsAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'tools',
  parts: [
    { id: 'root' },
    { id: 'toolSuite' },
    { id: 'toolSuiteHero' },
    { id: 'toolSuiteHeroCopy' },
    { id: 'toolSuiteHeroActions' },
    { id: 'toolSuiteModeToolbar' },
    { id: 'toolSuiteModes' },
    { id: 'toolSuiteModeTab' },
    { id: 'toolSuiteModeTabLabel' },
    { id: 'toolSuiteLoading' },
    { id: 'toolSuiteError' },
    { id: 'toolSuiteEmpty' },
    { id: 'toolSuiteSections' },
    { id: 'toolSuiteSection' },
    { id: 'toolSuiteSectionLabel' },
    { id: 'toolSuiteGrid' },
    { id: 'toolSuiteGroupCard' },
    { id: 'toolSuiteGroupHead' },
    { id: 'toolSuiteGroupTitleWrap' },
    { id: 'toolSuiteGroupTitleRow' },
    { id: 'toolSuiteGroupTitle' },
    { id: 'toolSuiteGroupCount' },
    { id: 'toolSuiteGroupActions' },
    { id: 'toolSuiteTools' },
    { id: 'toolSuiteTool' },
    { id: 'toolSuiteToolName' },
    { id: 'toolSuiteToolStatus' },
  ],
  facets: [
    { id: 'mode', attribute: 'data-bf-mode', values: ['agentic', 'Cowork', 'Claw', 'Team'] },
  ],
  states: [
    { id: 'hover', selector: { kind: 'self', suffix: ':hover' } },
    { id: 'focusVisible', selector: { kind: 'self', suffix: ':focus-visible' } },
    { id: 'disabled', selector: { kind: 'self', suffix: ':disabled' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-bf-state~="active"]' } },
    { id: 'enabled', selector: { kind: 'self', suffix: '[data-bf-state~="enabled"]' } },
    { id: 'dirty', selector: { kind: 'self', suffix: '[data-bf-state~="dirty"]' } },
  ],
};
