import type { ComponentMeta } from "../../registry.types";

export const chatComposerMeta = {
  category: "flow-chat",
  description: "A slot-based FlowChat composer with a context bar and compact or expanded input anatomy.",
  maturity: "stable",
  name: "ChatComposer",
  props: [
    { defaultValue: "compact", name: "layout", type: "compact | expanded" },
    { name: "contextBar", type: "ReactNode" },
    { name: "children", type: "ReactNode" },
    { name: "startActions", type: "ReactNode" },
    { name: "endActions", type: "ReactNode" },
    { defaultValue: "false", name: "busy", type: "boolean" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
    { name: "surfaceClassName", type: "string" },
  ],
  states: ["default", "expanded", "focus-visible", "busy", "disabled"],
  tokens: [
    "border.width.default",
    "color.action.neutral.border",
    "color.border.default",
    "color.content.primary",
    "color.surface.panel",
    "control.chatComposer.compactGap",
    "control.chatComposer.compactHeight",
    "control.chatComposer.compactPaddingBlock",
    "control.chatComposer.compactPaddingInline",
    "control.chatComposer.compactTrackHeight",
    "control.chatComposer.controlHeight",
    "control.height.md",
    "font.family.control",
    "font.size.small",
    "font.weight.regular",
    "radius.2xl",
    "radius.pill",
    "shadow.base",
    "space.1",
    "space.2",
    "space.3",
    "space.6",
    "space.8",
    "space.12",
  ],
} as const satisfies ComponentMeta;
