use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::Command;

fn main() {
    emit_build_metadata();

    if let Err(e) = embed_cli_prompts() {
        eprintln!("Warning: Failed to embed CLI prompts: {}", e);
    }
}

fn emit_build_metadata() {
    println!("cargo:rerun-if-env-changed=BITFUN_CLI_BUILD_COMMIT");
    emit_git_rerun_paths();

    let commit = std::env::var("BITFUN_CLI_BUILD_COMMIT")
        .ok()
        .filter(|value| !value.trim().is_empty())
        .or_else(resolve_git_commit)
        .unwrap_or_else(|| "unknown".to_string());

    println!("cargo:rustc-env=BITFUN_CLI_BUILD_COMMIT={commit}");
}

fn emit_git_rerun_paths() {
    let Some(manifest_dir) = std::env::var("CARGO_MANIFEST_DIR").ok() else {
        return;
    };

    let git_dir = Command::new("git")
        .args(["-C", &manifest_dir, "rev-parse", "--git-dir"])
        .output()
        .ok()
        .and_then(|output| output.status.success().then_some(output.stdout))
        .and_then(|stdout| String::from_utf8(stdout).ok())
        .map(|value| value.trim().to_string())
        .filter(|value| !value.is_empty());

    let Some(git_dir) = git_dir else {
        return;
    };

    let git_dir = Path::new(&manifest_dir).join(git_dir);
    println!("cargo:rerun-if-changed={}", git_dir.join("HEAD").display());
    println!(
        "cargo:rerun-if-changed={}",
        git_dir.join("packed-refs").display()
    );

    if let Some(head_ref) = current_git_head_ref(&manifest_dir) {
        println!(
            "cargo:rerun-if-changed={}",
            git_dir.join(head_ref).display()
        );
    }
}

fn current_git_head_ref(manifest_dir: &str) -> Option<String> {
    let output = Command::new("git")
        .args(["-C", manifest_dir, "symbolic-ref", "--quiet", "HEAD"])
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let head_ref = String::from_utf8(output.stdout).ok()?.trim().to_string();
    (!head_ref.is_empty()).then_some(head_ref)
}

fn resolve_git_commit() -> Option<String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").ok()?;
    let output = Command::new("git")
        .args(["-C", &manifest_dir, "rev-parse", "--short=12", "HEAD"])
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let commit = String::from_utf8(output.stdout).ok()?.trim().to_string();
    (!commit.is_empty()).then_some(commit)
}

fn embed_cli_prompts() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let prompts_dir = Path::new(&manifest_dir).join("prompts");

    println!("cargo:rerun-if-changed=prompts");

    let mut prompts = HashMap::new();

    if prompts_dir.exists() {
        read_prompt_files(&prompts_dir, &prompts_dir, &mut prompts)?;
    }

    generate_prompts_code(&prompts)?;

    println!("Embedded {} CLI prompt(s)", prompts.len());
    Ok(())
}

fn read_prompt_files(
    current_dir: &Path,
    base_dir: &Path,
    prompts: &mut HashMap<String, String>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(current_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            read_prompt_files(&path, base_dir, prompts)?;
        } else if matches!(
            path.extension().and_then(|e| e.to_str()),
            Some("md" | "txt")
        ) {
            let content = fs::read_to_string(&path)?;
            let relative = path
                .strip_prefix(base_dir)?
                .to_string_lossy()
                .replace('\\', "/");
            // Key: filename without extension, e.g. "init" from "init.md"
            let key = relative
                .trim_end_matches(".md")
                .trim_end_matches(".txt")
                .to_string();
            prompts.insert(key, content);
        }
    }
    Ok(())
}

fn generate_prompts_code(
    prompts: &HashMap<String, String>,
) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("embedded_cli_prompts.rs");
    let mut f = fs::File::create(&dest)?;

    writeln!(f, "// Auto-generated by build.rs — do not edit")?;
    writeln!(f)?;
    writeln!(f, "use std::collections::HashMap;")?;
    writeln!(f, "use once_cell::sync::Lazy;")?;
    writeln!(f)?;
    writeln!(
        f,
        "pub static CLI_PROMPTS: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {{"
    )?;
    writeln!(f, "    let mut m = HashMap::new();")?;

    for (key, content) in prompts {
        writeln!(
            f,
            "    m.insert(r###\"{}\"###, r###\"{}\"###);",
            key, content
        )?;
    }

    writeln!(f, "    m")?;
    writeln!(f, "}});")?;
    writeln!(f)?;

    writeln!(f, "/// Get an embedded CLI prompt by name")?;
    writeln!(
        f,
        "pub fn get_cli_prompt(name: &str) -> Option<&'static str> {{"
    )?;
    writeln!(f, "    CLI_PROMPTS.get(name).copied()")?;
    writeln!(f, "}}")?;

    Ok(())
}
