use serde::{Deserialize, Serialize};
use std::collections::HashSet;

/// A trading strategy hypothesis generated by LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Hypothesis {
    pub name: String,
    pub description: String,
    /// Entry conditions (max 5, enforced by Validator).
    pub entry_conditions: Vec<Condition>,
    /// Exit conditions.
    pub exit_conditions: Vec<Condition>,
    pub position_sizing: PositionSizing,
    pub risk_params: RiskParams,
    pub instruments: Vec<String>,
}

/// A single entry or exit condition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Condition {
    /// Indicator name: "MA", "RSI", "MACD", "Bollinger", etc.
    pub indicator: String,
    /// Indicator parameters as key-value pairs.
    pub params: serde_json::Value,
    /// Comparison operator: ">", "<", "cross_above", "cross_below".
    pub operator: String,
    /// Threshold value.
    pub value: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PositionSizing {
    /// Method: "fixed", "kelly", "risk_percent".
    pub method: String,
    pub value: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stop_loss: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub take_profit: Option<f64>,
    pub max_holding_bars: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_drawdown: Option<f64>,
}

impl Default for Hypothesis {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            entry_conditions: Vec::new(),
            exit_conditions: Vec::new(),
            position_sizing: PositionSizing {
                method: "fixed".into(),
                value: 1.0,
            },
            risk_params: RiskParams {
                stop_loss: None,
                take_profit: None,
                max_holding_bars: 20,
                max_drawdown: None,
            },
            instruments: Vec::new(),
        }
    }
}

// ── Validator ──

/// Indicators that inherently require future data (look-ahead bias).
const LOOKAHEAD_INDICATORS: &[&str] = &[
    "zigzag",
    "ref_future",
    "future_ref",
    "repaint",
    "future",
    "ref+",
];

/// Indicators whose params may encode forward-looking behavior.
const LOOKAHEAD_PARAM_PATTERNS: &[(&str, &str)] = &[
    ("repaint", "true"),
    ("lookahead", "true"),
    ("future_bars", ""), // any positive value is suspect
];

pub struct HypothesisValidator {
    /// Set of indicator names registered in taiji-engine.
    registered_indicators: HashSet<String>,
}

impl HypothesisValidator {
    pub fn new(registered_indicators: Vec<String>) -> Self {
        Self {
            registered_indicators: registered_indicators.into_iter().collect(),
        }
    }

    /// Full validation: type checks, reasonability, look-ahead bias.
    pub fn validate(&self, hypothesis: &Hypothesis) -> ValidationReport {
        let mut errors: Vec<String> = Vec::new();
        let mut warnings: Vec<String> = Vec::new();

        // Reasonability
        if let Err(e) = self.check_reasonability(hypothesis) {
            errors.push(e);
        }

        // Look-ahead bias
        match self.check_lookahead_bias(hypothesis) {
            Ok(()) => {}
            Err(e) => errors.push(e),
        }

        // Type checks
        if hypothesis.name.is_empty() {
            errors.push("hypothesis.name is required".into());
        }
        if hypothesis.instruments.is_empty() {
            errors.push("at least one instrument is required".into());
        }
        if hypothesis.entry_conditions.is_empty() {
            errors.push("at least one entry condition is required".into());
        }
        if hypothesis.entry_conditions.len() > 5 {
            errors.push(format!(
                "max 5 entry conditions, got {}",
                hypothesis.entry_conditions.len()
            ));
        }
        if hypothesis.entry_conditions.len() + hypothesis.exit_conditions.len() > 8 {
            warnings.push(format!(
                "total conditions ({}) exceeds recommended max of 8 adjustable params",
                hypothesis.entry_conditions.len() + hypothesis.exit_conditions.len()
            ));
        }

        for (i, cond) in hypothesis.entry_conditions.iter().enumerate() {
            if cond.indicator.is_empty() {
                errors.push(format!("entry_condition[{}].indicator is empty", i));
            }
            if !self.registered_indicators.is_empty()
                && !self.registered_indicators.contains(&cond.indicator)
            {
                warnings.push(format!(
                    "entry_condition[{}].indicator '{}' is not in registered indicator list",
                    i, cond.indicator
                ));
            }
            match cond.operator.as_str() {
                ">" | "<" | "cross_above" | "cross_below" => {}
                "" => {
                    errors.push(format!("entry_condition[{}].operator is empty", i));
                }
                other => {
                    warnings.push(format!(
                        "entry_condition[{}].operator '{}' is non-standard",
                        i, other
                    ));
                }
            }
        }

        for (i, cond) in hypothesis.exit_conditions.iter().enumerate() {
            if cond.indicator.is_empty() {
                errors.push(format!("exit_condition[{}].indicator is empty", i));
            }
            match cond.operator.as_str() {
                ">" | "<" | "cross_above" | "cross_below" => {}
                "" => {
                    errors.push(format!("exit_condition[{}].operator is empty", i));
                }
                other => {
                    warnings.push(format!(
                        "exit_condition[{}].operator '{}' is non-standard",
                        i, other
                    ));
                }
            }
        }

        let lookahead_free = errors.iter().all(|e| !e.contains("look-ahead"));

        ValidationReport {
            is_valid: errors.is_empty(),
            errors,
            warnings,
            lookahead_free,
        }
    }

    /// Detect look-ahead bias: conditions that reference future bar data.
    ///
    /// Checks:
    /// 1. Indicator name in known look-ahead list (zigzag, ref+, etc.)
    /// 2. Indicator params with repaint/lookahead flags
    /// 3. Conditions that explicitly reference "future" in indicator name or params
    pub fn check_lookahead_bias(&self, hypothesis: &Hypothesis) -> Result<(), String> {
        let all_conditions = hypothesis
            .entry_conditions
            .iter()
            .chain(hypothesis.exit_conditions.iter());

        for cond in all_conditions {
            let indicator_lower = cond.indicator.to_lowercase();

            // Check known look-ahead indicator names
            for la_name in LOOKAHEAD_INDICATORS {
                if indicator_lower.contains(la_name) {
                    return Err(format!(
                        "look-ahead bias detected: indicator '{}' references future bar data (matches '{}')",
                        cond.indicator, la_name
                    ));
                }
            }

            // Check params for repaint/lookahead flags
            if let Some(obj) = cond.params.as_object() {
                for (key, allowed_val) in LOOKAHEAD_PARAM_PATTERNS {
                    if let Some(val) = obj.get(*key) {
                        let match_found = if allowed_val.is_empty() {
                            // Any non-null/non-zero value is suspect
                            match val {
                                serde_json::Value::Bool(b) => *b,
                                serde_json::Value::Number(n) => n.as_f64().is_some_and(|f| f > 0.0),
                                serde_json::Value::String(s) => !s.is_empty() && s != "false",
                                _ => true,
                            }
                        } else {
                            val.as_str().map_or(
                                // Also check boolean true
                                val.as_bool() == Some(true),
                                |s| s == *allowed_val,
                            )
                        };
                        if match_found {
                            return Err(format!(
                                "look-ahead bias detected: condition '{}' has param {}.{}={} which indicates forward-looking behavior",
                                cond.indicator, key, allowed_val, val
                            ));
                        }
                    }
                }
            }
        }

        Ok(())
    }

    /// Basic reasonability checks on the hypothesis.
    pub fn check_reasonability(&self, hypothesis: &Hypothesis) -> Result<(), String> {
        // Stop loss must be below entry (for long) — structural check only
        if let Some(sl) = hypothesis.risk_params.stop_loss {
            if sl <= 0.0 {
                return Err("stop_loss must be positive".into());
            }
        }
        if let Some(tp) = hypothesis.risk_params.take_profit {
            if tp <= 0.0 {
                return Err("take_profit must be positive".into());
            }
        }
        if hypothesis.risk_params.max_holding_bars == 0 {
            return Err("max_holding_bars must be >= 1".into());
        }
        if hypothesis.position_sizing.value <= 0.0 {
            return Err("position_sizing.value must be positive".into());
        }
        match hypothesis.position_sizing.method.as_str() {
            "fixed" | "kelly" | "risk_percent" => {}
            other => {
                return Err(format!(
                    "unknown position_sizing method '{}' (expected: fixed, kelly, risk_percent)",
                    other
                ));
            }
        }
        Ok(())
    }
}

#[derive(Debug, Clone)]
pub struct ValidationReport {
    pub is_valid: bool,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
    pub lookahead_free: bool,
}

// ── Tests ──

#[cfg(test)]
mod tests {
    use super::*;

    fn make_simple_hypothesis() -> Hypothesis {
        Hypothesis {
            name: "test_ma_cross".into(),
            description: "MA crossover strategy".into(),
            entry_conditions: vec![Condition {
                indicator: "MA".into(),
                params: serde_json::json!({"period": 5}),
                operator: "cross_above".into(),
                value: 0.0,
            }],
            exit_conditions: vec![Condition {
                indicator: "MA".into(),
                params: serde_json::json!({"period": 20}),
                operator: "cross_below".into(),
                value: 0.0,
            }],
            position_sizing: PositionSizing {
                method: "fixed".into(),
                value: 1.0,
            },
            risk_params: RiskParams {
                stop_loss: Some(50.0),
                take_profit: Some(100.0),
                max_holding_bars: 20,
                max_drawdown: None,
            },
            instruments: vec!["rb9999".into()],
        }
    }

    #[test]
    fn test_valid_hypothesis_passes() {
        let validator = HypothesisValidator::new(vec!["MA".into(), "RSI".into()]);
        let h = make_simple_hypothesis();
        let report = validator.validate(&h);
        assert!(report.is_valid, "errors: {:?}", report.errors);
        assert!(report.lookahead_free);
    }

    #[test]
    fn test_lookahead_bias_zigzag() {
        let validator = HypothesisValidator::new(vec!["zigzag".into()]);
        let h = Hypothesis {
            entry_conditions: vec![Condition {
                indicator: "zigzag".into(),
                params: serde_json::json!({}),
                operator: ">".into(),
                value: 0.0,
            }],
            ..make_simple_hypothesis()
        };
        let report = validator.validate(&h);
        assert!(!report.is_valid);
        assert!(!report.lookahead_free);
        assert!(
            report.errors.iter().any(|e| e.contains("look-ahead")),
            "expected look-ahead error in: {:?}",
            report.errors
        );
    }

    #[test]
    fn test_lookahead_bias_ref_future() {
        let validator = HypothesisValidator::new(vec!["ref_future".into()]);
        let h = Hypothesis {
            entry_conditions: vec![Condition {
                indicator: "ref_future".into(),
                params: serde_json::json!({"offset": 1}),
                operator: ">".into(),
                value: 0.0,
            }],
            ..make_simple_hypothesis()
        };
        let report = validator.validate(&h);
        assert!(!report.is_valid);
        assert!(!report.lookahead_free);
    }

    #[test]
    fn test_lookahead_bias_repaint_param() {
        let validator = HypothesisValidator::new(vec!["MA".into()]);
        let h = Hypothesis {
            entry_conditions: vec![Condition {
                indicator: "MA".into(),
                params: serde_json::json!({"period": 5, "repaint": true}),
                operator: ">".into(),
                value: 0.0,
            }],
            ..make_simple_hypothesis()
        };
        let report = validator.validate(&h);
        assert!(!report.is_valid);
        assert!(!report.lookahead_free);
    }

    #[test]
    fn test_max_entry_conditions_enforced() {
        let validator = HypothesisValidator::new(vec!["MA".into()]);
        let mut h = make_simple_hypothesis();
        h.entry_conditions = (0..6)
            .map(|i| Condition {
                indicator: "MA".into(),
                params: serde_json::json!({"period": i}),
                operator: ">".into(),
                value: 0.0,
            })
            .collect();
        let report = validator.validate(&h);
        assert!(!report.is_valid);
        assert!(report.errors.iter().any(|e| e.contains("max 5")));
    }

    #[test]
    fn test_empty_name_rejected() {
        let validator = HypothesisValidator::new(vec![]);
        let mut h = make_simple_hypothesis();
        h.name.clear();
        let report = validator.validate(&h);
        assert!(!report.is_valid);
    }

    #[test]
    fn test_reasonability_negative_stop_loss() {
        let validator = HypothesisValidator::new(vec![]);
        let mut h = make_simple_hypothesis();
        h.risk_params.stop_loss = Some(-10.0);
        let report = validator.validate(&h);
        assert!(!report.is_valid);
    }

    #[test]
    fn test_reasonability_bad_position_method() {
        let validator = HypothesisValidator::new(vec![]);
        let mut h = make_simple_hypothesis();
        h.position_sizing.method = "martingale".into();
        let report = validator.validate(&h);
        assert!(!report.is_valid);
    }
}
