import type { ComponentMeta } from "../../registry.types";

export const fieldMeta = {
  category: "form",
  description: "Associates label content, optional actions, description, and adjacent controls with one primary form control.",
  maturity: "stable",
  name: "Field",
  props: [
    { name: "label", type: "ReactNode" },
    { name: "description", type: "ReactNode" },
    { name: "labelAction", type: "ReactNode" },
    { name: "controlLeading", type: "ReactNode" },
    { name: "controlTrailing", type: "ReactNode" },
    { defaultValue: "false", name: "required", type: "boolean" },
    { defaultValue: "vertical", name: "orientation", type: "horizontal | vertical" },
    { name: "children", type: "ReactElement" },
  ],
  states: ["default"],
  tokens: [
    "color.accent.default",
    "color.content.primary",
    "color.content.muted",
    "layout.field.rootGap",
    "layout.field.horizontalGap",
    "layout.field.contentGap",
    "layout.field.labelGap",
    "layout.field.labelActionGap",
    "layout.field.controlGap",
    "font.family.control",
    "font.size.caption",
    "font.size.small",
    "font.weight.regular",
    "font.weight.semibold",
  ],
} as const satisfies ComponentMeta;
