import type { ComponentMeta } from "../../registry.types";

export const menuMeta = {
  category: "navigation",
  description: "A grouped, scrollable menu surface with native item roles and keyboard navigation.",
  maturity: "stable",
  name: "Menu",
  props: [
    { name: "children", type: "ReactNode" },
    { defaultValue: "false", name: "autoFocusFirstItem", type: "boolean" },
    { defaultValue: "auto", name: "scrollbarVisibility", type: "auto | always | hidden" },
  ],
  states: ["default", "scrolling", "focus-within", "disabled-item", "checked-item"],
  tokens: [
    "color.surface.panel",
    "color.border.subtle",
    "color.content.muted",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfacePressed",
    "color.focus.ring",
    "overlay.menu.inlineSize",
    "overlay.menu.maxBlockSize",
    "overlay.menu.surfacePadding",
    "overlay.menu.surfaceRadius",
    "overlay.menu.sectionGap",
    "overlay.menu.headingHeight",
    "overlay.menu.headingPaddingInline",
    "overlay.menu.headingGap",
    "overlay.menu.headingFontSize",
    "overlay.menu.headingActionSize",
    "overlay.menu.itemHeight",
    "overlay.menu.itemPaddingInline",
    "overlay.menu.itemGap",
    "overlay.menu.itemRadius",
    "overlay.menu.itemIconSize",
    "overlay.menu.scrollbarGap",
    "scrollbar.width",
    "scrollbar.radius",
    "shadow.menu",
  ],
} as const satisfies ComponentMeta;
