import type { ComponentMeta } from "../../registry.types";

export const comboboxMeta = {
  category: "form",
  description: "An anchored searchable selector with single, multiple, grouped, clearable, and custom-value modes.",
  maturity: "stable",
  name: "Combobox",
  props: [
    { name: "options", type: "readonly ComboboxOption[]" },
    { name: "value", type: "ComboboxValue | ComboboxValue[]" },
    { defaultValue: "false", name: "searchable", type: "boolean" },
    { defaultValue: "false", name: "multiple", type: "boolean" },
    { defaultValue: "false", name: "clearable", type: "boolean" },
    { defaultValue: "false", name: "allowCustomValue", type: "boolean" },
    { defaultValue: "md", name: "size", type: "sm | md | lg" },
  ],
  states: ["default", "open", "searching", "multiple", "invalid", "disabled", "loading"],
  tokens: [
    "color.field.background",
    "color.field.backgroundHover",
    "color.field.border",
    "color.field.borderHover",
    "color.field.borderFocus",
    "color.content.primary",
    "color.content.secondary",
    "color.content.muted",
    "color.content.disabled",
    "color.action.neutral.content",
    "color.action.neutral.surface",
    "color.border.subtle",
    "color.surface.panel",
    "color.focus.ring",
    "color.status.danger.border",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "control.select.paddingInline",
    "control.select.radius",
    "control.select.indicatorSize",
    "control.select.contentGap",
    "overlay.menu.inlineSize",
    "overlay.menu.surfacePadding",
    "overlay.menu.surfaceRadius",
    "overlay.menu.itemIconSize",
    "shadow.menu",
  ],
} as const satisfies ComponentMeta;
