import type { ComponentMeta } from "../../registry.types";

export const modalMeta = {
  category: "feedback",
  description: "A blocking, portaled dialog with injectable host, focus management, responsive sizing, and configurable surface geometry.",
  maturity: "stable",
  name: "Modal",
  props: [
    { name: "isOpen", type: "boolean" },
    { name: "onClose", type: "() => void" },
    { name: "title", type: "ReactNode" },
    { defaultValue: "medium", name: "size", type: "small | medium | large | xlarge | xxlarge | wide" },
    { defaultValue: "xl", name: "radius", type: "base | lg | xl | 2xl | 3xl | 4xl" },
    { defaultValue: "none", name: "contentPadding", type: "none | sm | md | lg | xl" },
    { defaultValue: "none", name: "backdropBlur", type: "none | subtle | base" },
    { defaultValue: "overlay", name: "elevation", type: "none | raised | overlay" },
    { defaultValue: "true", name: "showCloseButton", type: "boolean" },
    { defaultValue: "true", name: "closeOnOverlayClick", type: "boolean" },
    { defaultValue: "true", name: "closeOnEscape", type: "boolean" },
    { defaultValue: "false", name: "draggable", type: "boolean" },
    { defaultValue: "false", name: "resizable", type: "boolean" },
  ],
  states: ["open", "exiting", "focus-trapped", "draggable", "dragging", "resizable", "resizing"],
  tokens: [
    "color.overlay.scrim",
    "color.surface.raised",
    "color.border.subtle",
    "color.content.secondary",
    "overlay.modal.viewportGutter",
    "overlay.modal.edgeGutter",
    "overlay.modal.contentPaddingSm",
    "overlay.modal.contentPaddingMd",
    "overlay.modal.contentPaddingLg",
    "overlay.modal.contentPaddingXl",
    "overlay.modal.maxInlineSizeSmall",
    "overlay.modal.maxInlineSizeMedium",
    "overlay.modal.maxInlineSizeLarge",
    "overlay.modal.maxInlineSizeXlarge",
    "overlay.modal.maxInlineSizeXxlarge",
    "overlay.modal.maxInlineSizeWide",
    "radius.base",
    "radius.lg",
    "radius.xl",
    "radius.2xl",
    "radius.3xl",
    "radius.4xl",
    "shadow.raised",
    "shadow.overlay",
  ],
} as const satisfies ComponentMeta;
