import type { ComponentMeta } from "../../registry.types";

export const modalMeta = {
  category: "feedback",
  description: "A blocking, portaled dialog with focus management, configurable surface geometry, semantic header content, and a floating action footer.",
  maturity: "stable",
  name: "Modal",
  props: [
    { name: "isOpen", type: "boolean" },
    { name: "onClose", type: "() => void" },
    { name: "title", type: "ReactNode" },
    { name: "description", type: "ReactNode" },
    { name: "headerActions", type: "ReactNode" },
    { name: "footer", type: "ReactNode" },
    { defaultValue: "medium", name: "size", type: "small | medium | large | xlarge | xxlarge | wide" },
    { defaultValue: "xl", name: "radius", type: "base | lg | xl | 2xl | 3xl | 4xl" },
    { defaultValue: "none", name: "contentPadding", type: "none | sm | md | lg | xl" },
    { defaultValue: "none", name: "backdropBlur", type: "none | subtle | base" },
    { defaultValue: "overlay", name: "elevation", type: "none | raised | overlay" },
    { defaultValue: "true", name: "showCloseButton", type: "boolean" },
    { defaultValue: "true", name: "closeOnOverlayClick", type: "boolean" },
    { defaultValue: "true", name: "closeOnEscape", type: "boolean" },
    { defaultValue: "true", name: "autoFocus", type: "boolean" },
    { name: "initialFocusRef", type: "RefObject<HTMLElement | null>" },
    { defaultValue: "true", name: "preventScroll", type: "boolean" },
    { defaultValue: "true", name: "showScrollbar", type: "boolean" },
    { name: "closeIcon", type: "ReactNode" },
    { name: "closeButtonProps", type: "IconButtonProps" },
    { defaultValue: "false", name: "draggable", type: "boolean" },
    { defaultValue: "false", name: "resizable", type: "boolean" },
  ],
  states: ["open", "exiting", "focus-trapped", "draggable", "dragging", "resizable", "resizing"],
  tokens: [
    "color.overlay.scrim",
    "color.surface.raised",
    "color.border.subtle",
    "color.content.secondary",
    "overlay.modal.viewportGutter",
    "overlay.modal.edgeGutter",
    "overlay.modal.contentPaddingSm",
    "overlay.modal.contentPaddingMd",
    "overlay.modal.contentPaddingLg",
    "overlay.modal.contentPaddingXl",
    "overlay.modal.descriptionGap",
    "overlay.modal.headerActionsGap",
    "overlay.modal.footerGap",
    "overlay.modal.footerPaddingBlockStart",
    "overlay.modal.footerPaddingBlockEnd",
    "overlay.modal.footerPaddingInline",
    "overlay.modal.footerHeight",
    "overlay.modal.footerContentInset",
    "overlay.modal.footerBlur",
    "overlay.modal.footerActionMinWidth",
    "overlay.modal.maxInlineSizeSmall",
    "overlay.modal.maxInlineSizeMedium",
    "overlay.modal.maxInlineSizeLarge",
    "overlay.modal.maxInlineSizeXlarge",
    "overlay.modal.maxInlineSizeXxlarge",
    "overlay.modal.maxInlineSizeWide",
    "radius.base",
    "radius.lg",
    "radius.xl",
    "radius.2xl",
    "radius.3xl",
    "radius.4xl",
    "shadow.raised",
    "shadow.overlay",
  ],
} as const satisfies ComponentMeta;
